# tasks/install.yml
#
# Marathon configuration and installation
---

- name: Add apt_key for marathon
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=E56151BF
  tags:
    - configuration

- name: Add mesosphere repository source  
  apt_repository: repo="deb http://repos.mesosphere.com/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main" state=present
  tags:
    - configuration

- name: Installation of open-jdk-8 and Marathon
  apt: name={{item}} update_cache=yes
  with_items:
    - openjdk-8-jre-headless
    - marathon
  register: job_result
  until: job_result|success
  retries: 3
  tags:
    - packages

- name: Copy marathon configuration file
  template: src=default_marathon_conf.j2 dest=/etc/default/marathon
  tags:
    - configuration

    
- name: Start marathon
  service: name=marathon state=started
  tags:
    - configuration
