# Author : zagabe.ed@gmail.com
#
# Here is the list of tasks to install and configure
# Marathon
#

# Add the jessie-backports repository
- name: Add jessie-backports repo
  apt_repository: repo="deb http://http.debian.net/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}}-backports main" state=present

# Installation of Marathon and its dependencies
- name: Installation of open-jdk-8 and Marathon
  apt: name={{item}} update_cache=yes
  with_items:
    - openjdk-8-jre-headless
    - marathon

# Create all the configuration folders
- name: Creating configuration folders
  file: path={{item}} state=directory mode=0755
  with_items:
    - "/etc/sysconfig"
    - "/etc/marathon"
    - "/etc/marathon/conf"

# Copy marathon configuration file
- name: Copy the /etc/sysconfig/marathon file
  template: src=marathon.j2 dest=/etc/sysconfig/marathon

# Copy master configuration file which is the mesos masters URLs
- name: Copy the /etc/marathon/conf/master
  template: src=master.j2 dest=/etc/marathon/conf/master

# Copy zk configuration file which is the zookeepers URLs
- name: Copy the /etc/marathon/conf/zk
  template: src=zk.j2 dest=/etc/marathon/conf/zk

# Copy http_port configuration file which is the port listened by Marathon
- name: Copy the /etc/marathon/conf/http_port
  template: src=http_port.j2 dest=/etc/marathon/conf/http_port
  notify:
    - Start marathon