# tasks/install.yml
#
# Golang configuration and installation
---

- name: Golang dependencies installation
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - build-essential
    - git
    - wget
  register: job_result
  until: job|success
  retries: 3
  tags:
    - packages

- name: Golang src downloading
  command: wget {{go_download_location}} -P /tmp
  register: job_result
  until: job|success
  retries: 3
  tags:
    - packages

- name: Golang tarball extraction
  command: tar -C /usr/local -xf /tmp/{{go_tarball}}
  tags:
    - configuration

- name: Gopath directory creation
  file: path={{go_path}} state=directory
  tags:
    - configuration

- name: Go bin symlink creation
  file: src=/usr/local/go/bin/go dest=/usr/local/bin/go state=link
  tags:
    - configuration

- name: Golang environment script creation
  template: src=golang-path.sh.j2 dest=/etc/profile.d/golang-path.sh
  tags:
    - configuration
