# tasks/main.yml
#
# Hostname configuration
---

- name: Update the hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
  tags:
    - configuration

- name: Update IPv4 hostname /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{var_hostname}}{{'\t'}}localhost{{'\t'}}localhost.localdomain{{'\n'}}"
  tags:
    - configuration

- name: Update IPv6 hostname /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^::1"
    line: "::1{{'\t'}}{{var_hostname}}{{'\t'}}localhost{{'\t'}}ip6-localhost{{'\t'}}ip6-loopback"
  tags:
    - configuration

- name: Restart remote hosts
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ingore_errors: true
  tags:
    - configuration
    
- name: Waiting for servers to come back
  local_action: wait_for host={{ inventory_hostname }} state=started
  sudo: false
  tags:
    - configuration
