#
# Hostname configuration
#

- name: Update the hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644

- name: Update IPv4 hostname /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{var_hostname}}{{'\t'}}localhost{{'\t'}}localhost.localdomain{{'\n'}}"

- name: Update IPv6 hostname /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^::1"
    line: "::1{{'\t'}}{{var_hostname}}{{'\t'}}localhost{{'\t'}}ip6-localhost{{'\t'}}ip6-loopback"

#TODO(eddyzags): Find another approach to update the hostname
- name: Restart remote hosts
  command: shutdown -r now "Ansible updates triggered"
    
- name: Reload network configuration (waiting 1m20s)
  pause: minutes=1 seconds=20
