# install.yml
#
# Cluster deployment playbook
---

- name: Default configuration
  hosts: all
  any_errors_fatal: true
  sudo: yes
  vars:
    cluster_name: galaxy
    playbook_mode: "install"
    mesos_mode: "master-slave"
  roles:
    - apt
    - sudoers
    - users
    - docker
    - docker-registry
    - zookeeper
    - mesos
    - marathon
