#
# Playbooks used by ansible for the infrastructure
# configuration and deployment.
#
#
# PLEASE MAKE SURE THAT YOUR CONFIGURATIONS ARE ALL WELL-DEFINED IN THE APPROPRIATE
# ROLES FOLDER

- name : Server configuration
  hosts : all
  sudo : yes
  roles :
    - users
    - sudoers
    - apt
    - docker
    
- name: Apache Zookeeper
  hosts: zookeeper
  sudo: yes
  roles:
    - zookeeper
    
- name: Apache Mesos
  hosts: mesos
  sudo: yes
  vars:
    mesos_mode: master-slave
  roles:
    - mesos

- name: Marathon schedulers configuration/deployment
  hosts: marathon
  sudo: yes
  roles:
    - marathon
