# Author : zagabe.ed@gmail.com (Eddy ZAGABE)
#
# Playbooks used by ansible for the infrastructure
# configuration and deployment.
#
#
# PLEASE MAKE SURE THAT YOUR CONFIGURATIONS ARE ALL WELL-DEFINED IN THE APPROPRIATE
# ROLES FOLDER

# Main configuration on every targeted instances
- name : Server configuration
  hosts : all
  sudo : yes
  roles :
    - hostname
    - users
    - sudoers
    - apt
    - mesos-dns
    - docker
    
- name: Apache Zookeeper
  hosts: zookeeper
  sudo: yes
  roles:
    - zookeeper
    
- name: Apache Mesos MASTERS 
  hosts: mesos-master
  sudo: yes
  roles:
    - mesos

- name: Apache Mesos SLAVES
  hosts: mesos-slave
  sudo: yes
  roles:
    - mesos

- name: Marathon schedulers configuration/deployment
  hosts: marathon
  sudo: yes
  roles:
    - marathon