# install.yml

# Cluster deployment playbook
---

- name: Default configuration
  hosts: all
  any_errors_fatal: true
  sudo: yes
  vars:
    var_hostname: node
    playbook_mode: "install"
  roles:
    - sudoers
    - users
    - golang
    - zookeeper
    - mesos
    - marathon