# Author : zagabe.ed@gmail.com (Eddy ZAGABE)
#
# Here is the default file where all the variables
# for the docker role are defined
#

# Definition of the distribution for the repository source list
docker_distrib_repo: debian

# Definition of the release for the repository source list
docker_release_repo: jessie