# Author : zagabe.ed@gmail.com (Eddy ZAGABE)
#
# List of tasks for the configuration and and deployment
# of Mesos-DNS
#

# Removing bind9 for conflicts
- name: Remove package no needed
  apt: pkg="bind9" state=absent

# Transfert mesos-dns tarball
- name: Copy Mesos DNS tarball
  copy: src=mesos-dns.tar dest=/tmp/mesos-dns.tar

# Extract the download folder
- name: Extracting go distribution
  unarchive: src=/tmp/mesos-dns.tar dest=/usr/bin copy=no

# Copy config.json file
- name: Copy configuration file for Mesos DNS
  template: src=config.json.j2 dest="/tmp/config.json"

# Copy mesos-dns.service file
- name: Copy mesos-dns.service file
  template: src=mesos-dns.service.j2 dest="/lib/systemd/system/mesos-dns.service"

# Start Mesos-DNS service
- name: Start Mesos-DNS service
  service: name=mesos-dns state=started