# tasks/install.yml
#
# Mesos configuration and installation
---

- name: Add apt_key for repos.mesosphere.io repo
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=E56151BF
  tags:
    - configuration

- name: Add mesosphere repository
  apt_repository: repo="deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main" state=present
  tags:
    - configuration

- name: Mesos dependencies installation
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - python-setuptools
    - python-dev
    - python-pip
  register: job_result
  until: job_result|success
  retries: 3
  tags:
    - packages

- name: Apaches mesos installation
  apt: pkg="mesos" state=present install_recommends=no
  register: job_result
  until: job_result|success
  retries: 3
  tags:
    - packages
    
- name: Install mesos.cli
  pip: name=mesos.cli
  tags:
    - packages

- name: Copy mesos configuration
  template: src=default_mesos_conf.j2 dest=/etc/default/mesos
  tags:
    - configuration

- name: Copy mesos quorum configuraiton file
  template: src=quorum.j2 dest=/etc/mesos-master/quorum
  tags:
    - configuration

  
# Mesos master tasks
- name: Copy mesos-master configuration
  template: src=default_mesos_master_conf.j2 dest=/etc/default/mesos-master
  when: mesos_mode == "master" or mesos_mode == "master-slave"
  tags:
    - configuration

- name: Set the mesos-slave.override to manual
  template: src=manual.j2 dest=/etc/init/mesos-slave.override
  when: mesos_mode == "master"
  tags:
    - configuration
  
- name: Remove mesos-master.override
  file: path="/etc/init/mesos-master.override" state=absent
  when: mesos_mode == "master" or mesos_mode == "master-slave"
  tags:
    - configuration

- name: Stop mesos-slave service
  service: name=mesos-slave state=stopped
  when: mesos_mode == "master"
  tags:
    - configuration
  
- name: Start mesos-master
  service: name=mesos-master state=started
  when: mesos_mode == "master" or mesos_mode == "master-slave"
  tags:
    - configuration


# Mesos slave tasks
- name: Copy the mesos-slave configuration
  template: src=default_mesos_slave_conf.j2 dest=/etc/default/mesos-slave
  when: mesos_mode == "slave" or mesos_mode == "master-slave"
  tags:
    - configuration

- name: Copy mesos-master.override file
  template: src=manual.j2 dest=/etc/init/mesos-master.override
  when: mesos_mode == "slave"
  tags:
    - configuration

- name: Stop Mesos-master service
  service: name=mesos-master state=stopped
  when: mesos_mode == "slave"
  tags:
    - configuration

- name: Remove mesos-slave.override file
  file: path="/etc/init/mesos-slave.override" state=absent
  when: mesos_mode == "slave" or mesos_mode == "master-slave"
  tags:
    - configuration
  
- name: Start the mesos-slave service
  service: name=mesos-slave state=started
  when: mesos_mode == "slave" or mesos_mode == "master-slave"
  tags:
    - configuration
