# Author : zagabe.ed@gmail.com (Eddy ZAGABE)
#
# List of tasks for the installation of
# Apchage Mesos orchestrer.
#

# Add an apt key
- name: Add apt_key for repos.mesosphere.io repo
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

# Add repos.mesosphere.io repository
- name: Add mesosphere repository
  apt_repository: repo="deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main" state=present

# Install all the packages needed for mesos
- name: Install packages needed for mesos
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - python-pip

# Install Apache Mesos
- name: Install Apache Mesos
  apt: pkg="mesos" state=present install_recommends=no

# Install the mesos.cli to work with mesos
- name: Install mesos.cli
  pip: name=mesos.cli

# Remove configuration files
- name: Removing the configuration files
  file: path={{item}} state=absent
  with_items:
    - "/etc/mesos/zk"
    - "/etc/mesos-master/quorum"
    - "/etc/mesos-master/work_dir"
    - "/etc/mesos-slave/master"

# Copy the default mesos configuration
- name: Copy mesos configuration
  template: src=default_mesos_conf.j2 dest=/etc/default/mesos

  
## ALL THE TASKS HANDLE BY THE MESOS-MASTER GROUP
# Copy the default mesos-master configuration
- name: Copy mesos-master configuration
  template: src=default_mesos_master_conf.j2 dest=/etc/default/mesos-master

# Set the mesos-slave to manal initialization
- name: Set the mesos-slave.override to manual
  template: src=manual.j2 dest=/etc/init/mesos-slave.override
  when: "'mesos-slave' not in group_names"
  
# Removing the mesos-master.override if it exists
- name: Remove mesos-master.override
  file: path="/etc/init/mesos-master.override" state=absent
  when: "'mesos-master' in group_names"

# Stop mesos-slave service
- name: Stop mesos-slave service
  service: name=mesos-slave state=stopped
  when: "'mesos-slave' not in group_names"
  
# Start the mesos master
- name: Start mesos-master
  service: name=mesos-master state=started
  when: "'mesos-master' in group_names"


## ALL THE TASKS HANDLE BY THE MESOS-SLAVE GROUP  
# Copy the default mesos-slave configuration (only executed for the mesos-slave group)
- name: Copy the mesos-slave configuration
  template: src=default_mesos_slave_conf.j2 dest=/etc/default/mesos-slave

# Checking if Mesos-master is install on the remote hosts
- stat: path=/etc/init/mesos-slave.override
  register: slave_file
  
# Copy the mesos-master.override file so that it will not automatically start when the server
# reboots (only executed for the mesos-slave group)
- name: Copy mesos-master.override file
  template: src=manual.j2 dest=/etc/init/mesos-master.override
  when: "'mesos-master' not in group_names"

# Stop the Apache Mesos MASTER service (only executed for the mesos-slave group)
- name: Stop Mesos-master service
  service: name=mesos-master state=stopped
  when: "'mesos-master' not in group_names"

# Remove the mesos-slave.override file
- name: Remove mesos-slave.override file
  file: path="/etc/init/mesos-slave.override" state=absent
  when: "'mesos-slave' in group_names"
  
# Start the mesos-slave
- name: Start the mesos-slave service
  service: name=mesos-slave state=started
  when: "'mesos-slave' in group_names"

