# Author : zagabe.ed@gmail.com (Eddy ZAGABE)
#
# List of tasks for the installation of
# Apchage Mesos orchestrer.
#

# Add an apt key
- name: Add apt_key for repos.mesosphere.io repo
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

# Add repos.mesosphere.io repository
- name: Add mesosphere repository
  apt_repository: repo="deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main" state=present

# Install all the packages needed for mesos
- name: Install packages needed for mesos
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - python-pip
    - "mesos"

# Install the mesos.cli to work with mesos
- name: Install mesos.cli
  pip: name=mesos.cli

# Remove configuration files
- name: Removing the configuration files
  file: path={{item}} state=absent
  with_items:
    - "/etc/mesos/zk"
    - "/etc/mesos-master/quorum"
    - "/etc/mesos-master/work_dir"
    - "/etc/mesos-slave/master"

# Configure the /etc/mesos/zk which is the listing of
# zookeeper URLs
- name: Configure the /etc/mesos/zk file
  template: src=zk.j2 dest=/etc/mesos/zk

# Configure the /etc/mesos-master/quorum which is the number
# of master in the cluster
- name: Configure the /etc/mesos-master/quorum
  template: src=master_quorum.j2 dest=/etc/mesos-master/quorum

# Configure the /etc/mesos-master/work_dir which is the
# working directory of the master
- name: Configure the /etc/mesos-master/work_dir
  template: src=master_work_dir.j2 dest=/etc/mesos-master/work_dir
  notify:
    - Start mesos-master
    - Start mesos-slave